apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-hog-app
  namespace: production
  labels:
    scenario: cpu-throttling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-hog-app
  template:
    metadata:
      labels:
        app: cpu-hog-app
    spec:
      containers:
      - name: cpu-hog
        image: busybox
        command: ["sh", "-c", "while true; do :; done"]
        resources:
          limits:
            cpu: "50m"
            memory: "64Mi"
          requests:
            cpu: "50m"
            memory: "32Mi"
